import styles from "./styles.module.css";
import Header from "@/components/header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={styles.html} lang="en">
      <body className={styles.body}>
        <Header/>
        <div className={styles.parentContainer}>
        {children}
        </div>
      </body>
    </html>
  );
}
